[package]
name = "c-compiler"
version = "0.1.0"
authors = ["sushisyuki <ogiwara.yuki.sj@alumni.tsukuba.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"